export const NO_MULTIPLE_ANSWERS = 'NO_MULTIPLE_ANSWERS';
export const ANSWERS_NOT_UNIQUE = 'ANSWERS_NOT_UNIQUE';
export const TAGS_NOT_UNIQUE = 'TAGS_NOT_UNIQUE';
export const CORRECT_ANSWER_NOT_PRESENT_IN_ANSWERS =
  'CORRECT_ANSWER_NOT_PRESENT_IN_ANSWERS';
export const ADD_QUESTION_SUCCESS = 'ADD_ANSWER_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_ANSWER_FAILURE';
